{{- if .Values.multiContainer.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-test
  labels:
    app: multi-container
spec:
  containers:
  - name: app
    image: {{ .Values.multiContainer.appImage }}
    ports:
    - containerPort: {{ .Values.multiContainer.appPort }}
    command: ['sh', '-c', 'echo "App container started" && sleep 3600']
  - name: sidecar-logging
    image: {{ .Values.multiContainer.sidecarImage }}
    command: ['sh', '-c', 'while true; do echo "$(date) - Sidecar logging..."; sleep 5; done']
  - name: metrics
    image: {{ .Values.multiContainer.metricsImage }}
    ports:
    - containerPort: {{ .Values.multiContainer.metricsPort }}
    command: ['sh', '-c', 'echo "Metrics container started" && sleep 3600']
---
apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  selector:
    app: multi-container
  ports:
  - name: app
    protocol: TCP
    port: {{ .Values.multiContainer.appPort }}
    targetPort: {{ .Values.multiContainer.appPort }}
  - name: metrics
    protocol: TCP
    port: {{ .Values.multiContainer.metricsPort }}
    targetPort: {{ .Values.multiContainer.metricsPort }}
{{- end }}
