{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: redis-test
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: {{ .Values.redis.image }}
    ports:
    - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
{{- end }}
